- name: 'install the packages'
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
  when: "yumInstall"
  tags: always

- name: 'update all packages'
  yum:
    name: '*'
    state: latest
  when: "yumUpdate"
  tags: always
