---
- hosts: localhost
  tasks:
  - name: making a password less ssh connection from localhost
    include_role:
      name: password-less-ssh
    vars:
      password: "{{ vm_password }}"
      hosts: "{{ groups['all'] }}"
      key_gen: False
    tags: always

- hosts: all
  tasks:
  - name: subscription manager
    include_role:
      name: redhat_subscription
    vars:
      username: "{{ subscription_username }}"
      password: "{{ subscription_password }}"
      pool_ids: "{{ subscription_pool_ids }}"
      repos: "{{ subscription_repos }}"
    tags: subscription

  - name: yum install and update packages
    include_role:
      name: yum
    vars:
      packages: "{{ yum_packages }}"
      update: "{{ yum_update | default(True) }}"
    tags: yum

  - name: configure docker
    include_role:
      name: docker-setup
    vars:
      device: "{{ docker_device }}"
      vg: "{{ docker_vg }}"
    tags: docker

  - name: generate ssh key and make password less ssh connection b/w hosts
    include_role:
      name: password-less-ssh
    vars:
      password: "{{ vm_password }}"
      hosts: "{{ play_hosts }}"
    tags: ssh

  - name: reboot nodes and wait for it to come up
    include_role:
      name: node-reboot
    tags: reboot
