apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: config-maps-jjb
objects:
- apiVersion: v1
  data:
    jenkins_jobs.ini: |
      [jenkins]
      user=${JENKINS_USER}
      password=${JENKINS_PASSWORD}
      url=${JENKINS_URL}
      query_plugins_info=False
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: ${NAME}
parameters:
- description: Name of config map
  displayName: Config
  name: NAME
  required: true
  value: jjb-configmap
- description: Jenkins User
  displayName: Jenkins User
  name: JENKINS_USER
  required: true
  value: admin
- description: Jenkins Password
  displayName: Jenkins Password
  name: JENKINS_PASSWORD
  required: true
  value: password
- description: Jenkins URL
  displayName: Jenkins URL
  name: JENKINS_URL
  required: true
  value: https://jenkins-jenkins.router.default.svc.cluster.local
