- name: 'generating keys'
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa
  register: out
  vars:
    _key_gen: "{{ key_gen | default(True) }}"    
  when: "_key_gen"
  tags: always

- debug: var=out.stdout_lines
  tags: always

- name: 'making ssh less'
  command: sshpass -p "{{ password }}" ssh-copy-id -o \
      "StrictHostKeyChecking=no" -f "root@{{ item }}"
  with_items: "{{ hosts }}"
  tags: always
