- name: 'copy docker content in /etc/sysconfig/docker-storage-setup'
  copy:
    content: |
      DEVS={{ device }}
      VG={{ vg }}
    dest: /etc/sysconfig/docker-storage-setup
  tags: always

- name: 'configuring docker'
  command: docker-storage-setup
  register: out
  tags: always

- debug: var=out.stdout_lines
  tags: always

- name: 'enable docker service'
  command: "{{ item }}"
  with_items:
    - systemctl enable docker
    - systemctl start docker
    - systemctl is-active docker
  tags: always
